### ISSUE TITLE
Speedup inside kernel

### ISSUE THREAD

**Issue by varchasgopalaswamy** [Plasmacaster/Optimized_SavGol#1]
Unless I messed up, I think you can get a pretty nice speedup inside the kernel with this one simple trick

instead of 
```
filterArr = weightArr * signalSeg
filterSeg = np.sum(filterArr, axis=1)
# print(idx, m+1 + idx)
filterPoint = filterSeg[m + 1]
sgFilter[idx] = filterPoint

```

try 

```
sgFilter[idx] = np.sum(weightArr[m+1] * signalSeg)
```

Since you're only using the m+1 element of `filterSeg`, you might as well not compute the matrix vector produt.

**Comment by varchasgopalaswamy** [comment]
This should mainly affect cases where you have a large stencil, because of the time saving going from a mat-vec to a vec-vec product. 

![image](https://user-images.githubusercontent.com/2359219/160015354-2609855e-7a5f-4de2-b6aa-3b8bfa8b5709.png)

**Comment by Plasmacaster** [comment]
These changes have been implemented. Thanks!
